### ISSUE TITLE
asan: runtime error: reference binding to null pointer of type 'st_mysql_bind'

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet-insta/ddnet-insta#176]
# SAN_2ddfb6d0ace255caa8ba32ffc2c44562ef78f665_2024-10-03_16-24.3869682

gctf2 server

```
/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/stl_vector.h:1124:9: runtime error: reference binding to null pointer of type 'st_mysql_bind'
    #0 0x55555603576c in std::vector<st_mysql_bind, std::allocator<st_mysql_bind> >::operator[](unsigned long) /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/stl_vector.h:1124:2
    #1 0x55555602a777 in CMysqlConnection::PrepareStatement(char const*, char*, int) /home/chiller/git/ddnet-insta/src/engine/server/databases/mysql.cpp:334:12
    #2 0x55555669e1db in CSqlStats::CreateFastcapTableThread(IDbConnection*, ISqlData const*, Write, char*, int) /home/chiller/git/ddnet-insta/src/game/server/instagib/sql_stats.cpp:1072:17
    #3 0x555556007c2a in CDbConnectionPool::ExecSqlFunc(IDbConnection*, CSqlExecData*, Write) /home/chiller/git/ddnet-insta/src/engine/server/databases/connection_pool.cpp:454:14
    #4 0x555556009411 in CWorker::ProcessQueries() /home/chiller/git/ddnet-insta/src/engine/server/databases/connection_pool.cpp:338:12
    #5 0x555556007ff8 in CWorker::Start(void*) /home/chiller/git/ddnet-insta/src/engine/server/databases/connection_pool.cpp:271:9
    #6 0x555556ba5e81 in thread_run(void*) /home/chiller/git/ddnet-insta/src/base/system.cpp:779:2
    #7 0x7ffff73c9143 in start_thread nptl/./nptl/pthread_create.c:442:8
    #8 0x7ffff74497db in clone3 misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/stl_vector.h:1124:9 in 
/home/chiller/git/ddnet-insta/src/base/tl/../system.h:181:9: runtime error: null pointer passed as argument 1, which is declared to never be null
/usr/include/string.h:61:62: note: nonnull attribute specified here
    #0 0x5555560355ad in void mem_zero<st_mysql_bind>(st_mysql_bind*, unsigned long) /home/chiller/git/ddnet-insta/src/base/tl/../system.h:181:2
    #1 0x55555602a86c in CMysqlConnection::PrepareStatement(char const*, char*, int) /home/chiller/git/ddnet-insta/src/engine/server/databases/mysql.cpp:334:2
    #2 0x55555669e1db in CSqlStats::CreateFastcapTableThread(IDbConnection*, ISqlData const*, Write, char*, int) /home/chiller/git/ddnet-insta/src/game/server/instagib/sql_stats.cpp:1072:17
    #3 0x555556007c2a in CDbConnectionPool::ExecSqlFunc(IDbConnection*, CSqlExecData*, Write) /home/chiller/git/ddnet-insta/src/engine/server/databases/connection_pool.cpp:454:14
    #4 0x555556009411 in CWorker::ProcessQueries() /home/chiller/git/ddnet-insta/src/engine/server/databases/connection_pool.cpp:338:12
    #5 0x555556007ff8 in CWorker::Start(void*) /home/chiller/git/ddnet-insta/src/engine/server/databases/connection_pool.cpp:271:9
    #6 0x555556ba5e81 in thread_run(void*) /home/chiller/git/ddnet-insta/src/base/system.cpp:779:2
    #7 0x7ffff73c9143 in start_thread nptl/./nptl/pthread_create.c:442:8
    #8 0x7ffff74497db in clone3 misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/chiller/git/ddnet-insta/src/base/tl/../system.h:181:9 in 
/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/stl_vector.h:1124:9: runtime error: reference binding to null pointer of type 'CMysqlConnection::UParameterExtra'
    #0 0x555556035b8d in std::vector<CMysqlConnection::UParameterExtra, std::allocator<CMysqlConnection::UParameterExtra> >::operator[](unsigned long) /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/stl_vector.h:1124:2
    #1 0x55555602a94b in CMysqlConnection::PrepareStatement(char const*, char*, int) /home/chiller/git/ddnet-insta/src/engine/server/databases/mysql.cpp:335:12
    #2 0x55555669e1db in CSqlStats::CreateFastcapTableThread(IDbConnection*, ISqlData const*, Write, char*, int) /home/chiller/git/ddnet-insta/src/game/server/instagib/sql_stats.cpp:1072:17
    #3 0x555556007c2a in CDbConnectionPool::ExecSqlFunc(IDbConnection*, CSqlExecData*, Write) /home/chiller/git/ddnet-insta/src/engine/server/databases/connection_pool.cpp:454:14
    #4 0x555556009411 in CWorker::ProcessQueries() /home/chiller/git/ddnet-insta/src/engine/server/databases/connection_pool.cpp:338:12
    #5 0x555556007ff8 in CWorker::Start(void*) /home/chiller/git/ddnet-insta/src/engine/server/databases/connection_pool.cpp:271:9
    #6 0x555556ba5e81 in thread_run(void*) /home/chiller/git/ddnet-insta/src/base/system.cpp:779:2
    #7 0x7ffff73c9143 in start_thread nptl/./nptl/pthread_create.c:442:8
    #8 0x7ffff74497db in clone3 misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/stl_vector.h:1124:9 in 
/home/chiller/git/ddnet-insta/src/base/tl/../system.h:181:9: runtime error: null pointer passed as argument 1, which is declared to never be null
/usr/include/string.h:61:62: note: nonnull attribute specified here
    #0 0x5555560359cd in void mem_zero<CMysqlConnection::UParameterExtra>(CMysqlConnection::UParameterExtra*, unsigned long) /home/chiller/git/ddnet-insta/src/base/tl/../system.h:181:2
    #1 0x55555602aa43 in CMysqlConnection::PrepareStatement(char const*, char*, int) /home/chiller/git/ddnet-insta/src/engine/server/databases/mysql.cpp:335:2
    #2 0x55555669e1db in CSqlStats::CreateFastcapTableThread(IDbConnection*, ISqlData const*, Write, char*, int) /home/chiller/git/ddnet-insta/src/game/server/instagib/sql_stats.cpp:1072:17
    #3 0x555556007c2a in CDbConnectionPool::ExecSqlFunc(IDbConnection*, CSqlExecData*, Write) /home/chiller/git/ddnet-insta/src/engine/server/databases/connection_pool.cpp:454:14
    #4 0x555556009411 in CWorker::ProcessQueries() /home/chiller/git/ddnet-insta/src/engine/server/databases/connection_pool.cpp:338:12
    #5 0x555556007ff8 in CWorker::Start(void*) /home/chiller/git/ddnet-insta/src/engine/server/databases/connection_pool.cpp:271:9
    #6 0x555556ba5e81 in thread_run(void*) /home/chiller/git/ddnet-insta/src/base/system.cpp:779:2
    #7 0x7ffff73c9143 in start_thread nptl/./nptl/pthread_create.c:442:8
    #8 0x7ffff74497db in clone3 misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/chiller/git/ddnet-insta/src/base/tl/../system.h:181:9 in 
```

**Comment by ChillerDragon** [comment]
This can be closed if the error does not appear in any of the production servers in the next few days.

**Comment by ChillerDragon** [comment]
# SAN_f023e13d47e6e71c77aa20b473d1a5e24d0923af_2024-10-05_04-20.4029354

gctf2

Still not fixed with f023e13d47e6e71c77aa20b473d1a5e24d0923af

```
/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/stl_vector.h:1124:9: runtime error: reference binding to null pointer of type 'st_mysql_bind'
    #0 0x55555603b7ec in std::vector<st_mysql_bind, std::allocator<st_mysql_bind> >::operator[](unsigned long) /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/stl_vector.h:1124:2
    #1 0x5555560307f7 in CMysqlConnection::PrepareStatement(char const*, char*, int) /home/chiller/git/ddnet-insta/src/engine/server/databases/mysql.cpp:334:12
    #2 0x5555566abb44 in CSqlStats::CreateTableThread(IDbConnection*, ISqlData const*, Write, char*, int) /home/chiller/git/ddnet-insta/src/game/server/instagib/sql_stats.cpp:1027:17
    #3 0x55555600dcaa in CDbConnectionPool::ExecSqlFunc(IDbConnection*, CSqlExecData*, Write) /home/chiller/git/ddnet-insta/src/engine/server/databases/connection_pool.cpp:454:14
    #4 0x55555600f491 in CWorker::ProcessQueries() /home/chiller/git/ddnet-insta/src/engine/server/databases/connection_pool.cpp:338:12
    #5 0x55555600e078 in CWorker::Start(void*) /home/chiller/git/ddnet-insta/src/engine/server/databases/connection_pool.cpp:271:9
    #6 0x555556bb4df1 in thread_run(void*) /home/chiller/git/ddnet-insta/src/base/system.cpp:779:2
    #7 0x7ffff73c9143 in start_thread nptl/./nptl/pthread_create.c:442:8
    #8 0x7ffff74497db in clone3 misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/stl_vector.h:1124:9 in 
/home/chiller/git/ddnet-insta/src/base/tl/../system.h:181:9: runtime error: null pointer passed as argument 1, which is declared to never be null
/usr/include/string.h:61:62: note: nonnull attribute specified here
    #0 0x55555603b62d in void mem_zero<st_mysql_bind>(st_mysql_bind*, unsigned long) /home/chiller/git/ddnet-insta/src/base/tl/../system.h:181:2
    #1 0x5555560308ec in CMysqlConnection::PrepareStatement(char const*, char*, int) /home/chiller/git/ddnet-insta/src/engine/server/databases/mysql.cpp:334:2
    #2 0x5555566abb44 in CSqlStats::CreateTableThread(IDbConnection*, ISqlData const*, Write, char*, int) /home/chiller/git/ddnet-insta/src/game/server/instagib/sql_stats.cpp:1027:17
    #3 0x55555600dcaa in CDbConnectionPool::ExecSqlFunc(IDbConnection*, CSqlExecData*, Write) /home/chiller/git/ddnet-insta/src/engine/server/databases/connection_pool.cpp:454:14
    #4 0x55555600f491 in CWorker::ProcessQueries() /home/chiller/git/ddnet-insta/src/engine/server/databases/connection_pool.cpp:338:12
    #5 0x55555600e078 in CWorker::Start(void*) /home/chiller/git/ddnet-insta/src/engine/server/databases/connection_pool.cpp:271:9
    #6 0x555556bb4df1 in thread_run(void*) /home/chiller/git/ddnet-insta/src/base/system.cpp:779:2
    #7 0x7ffff73c9143 in start_thread nptl/./nptl/pthread_create.c:442:8
    #8 0x7ffff74497db in clone3 misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/chiller/git/ddnet-insta/src/base/tl/../system.h:181:9 in 
/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/stl_vector.h:1124:9: runtime error: reference binding to null pointer of type 'CMysqlConnection::UParameterExtra'
    #0 0x55555603bc0d in std::vector<CMysqlConnection::UParameterExtra, std::allocator<CMysqlConnection::UParameterExtra> >::operator[](unsigned long) /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/stl_vector.h:1124:2
    #1 0x5555560309cb in CMysqlConnection::PrepareStatement(char const*, char*, int) /home/chiller/git/ddnet-insta/src/engine/server/databases/mysql.cpp:335:12
    #2 0x5555566abb44 in CSqlStats::CreateTableThread(IDbConnection*, ISqlData const*, Write, char*, int) /home/chiller/git/ddnet-insta/src/game/server/instagib/sql_stats.cpp:1027:17
    #3 0x55555600dcaa in CDbConnectionPool::ExecSqlFunc(IDbConnection*, CSqlExecData*, Write) /home/chiller/git/ddnet-insta/src/engine/server/databases/connection_pool.cpp:454:14
    #4 0x55555600f491 in CWorker::ProcessQueries() /home/chiller/git/ddnet-insta/src/engine/server/databases/connection_pool.cpp:338:12
    #5 0x55555600e078 in CWorker::Start(void*) /home/chiller/git/ddnet-insta/src/engine/server/databases/connection_pool.cpp:271:9
    #6 0x555556bb4df1 in thread_run(void*) /home/chiller/git/ddnet-insta/src/base/system.cpp:779:2
    #7 0x7ffff73c9143 in start_thread nptl/./nptl/pthread_create.c:442:8
    #8 0x7ffff74497db in clone3 misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/stl_vector.h:1124:9 in 
/home/chiller/git/ddnet-insta/src/base/tl/../system.h:181:9: runtime error: null pointer passed as argument 1, which is declared to never be null
/usr/include/string.h:61:62: note: nonnull attribute specified here
    #0 0x55555603ba4d in void mem_zero<CMysqlConnection::UParameterExtra>(CMysqlConnection::UParameterExtra*, unsigned long) /home/chiller/git/ddnet-insta/src/base/tl/../system.h:181:2
    #1 0x555556030ac3 in CMysqlConnection::PrepareStatement(char const*, char*, int) /home/chiller/git/ddnet-insta/src/engine/server/databases/mysql.cpp:335:2
    #2 0x5555566abb44 in CSqlStats::CreateTableThread(IDbConnection*, ISqlData const*, Write, char*, int) /home/chiller/git/ddnet-insta/src/game/server/instagib/sql_stats.cpp:1027:17
    #3 0x55555600dcaa in CDbConnectionPool::ExecSqlFunc(IDbConnection*, CSqlExecData*, Write) /home/chiller/git/ddnet-insta/src/engine/server/databases/connection_pool.cpp:454:14
    #4 0x55555600f491 in CWorker::ProcessQueries() /home/chiller/git/ddnet-insta/src/engine/server/databases/connection_pool.cpp:338:12
    #5 0x55555600e078 in CWorker::Start(void*) /home/chiller/git/ddnet-insta/src/engine/server/databases/connection_pool.cpp:271:9
    #6 0x555556bb4df1 in thread_run(void*) /home/chiller/git/ddnet-insta/src/base/system.cpp:779:2
    #7 0x7ffff73c9143 in start_thread nptl/./nptl/pthread_create.c:442:8
    #8 0x7ffff74497db in clone3 misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/chiller/git/ddnet-insta/src/base/tl/../system.h:181:9 in 
```

**Comment by ChillerDragon** [comment]
1ce75183dff4c4c6452eaee83a286f0d083d797b

```
$ cat SAN_1ce75183dff4c4c6452eaee83a286f0d083d797b_2024-10-08_07-11.27105                                                                                                           
/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/stl_vector.h:1124:9: runtime error: reference binding to null pointer of type 'st_mysql_bind'                                              
    #0 0x55555604732c in std::vector<st_mysql_bind, std::allocator<st_mysql_bind> >::operator[](unsigned long) /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/stl_vector.h:1124:2         
    #1 0x55555603c337 in CMysqlConnection::PrepareStatement(char const*, char*, int) /home/chiller/git/ddnet-insta/src/engine/server/databases/mysql.cpp:334:12
    #2 0x5555566bfba4 in CSqlStats::CreateTableThread(IDbConnection*, ISqlData const*, Write, char*, int) /home/chiller/git/ddnet-insta/src/game/server/instagib/sql_stats.cpp:1027:17
    #3 0x5555560197ea in CDbConnectionPool::ExecSqlFunc(IDbConnection*, CSqlExecData*, Write) /home/chiller/git/ddnet-insta/src/engine/server/databases/connection_pool.cpp:454:14
    #4 0x55555601afd1 in CWorker::ProcessQueries() /home/chiller/git/ddnet-insta/src/engine/server/databases/connection_pool.cpp:338:12
    #5 0x555556019bb8 in CWorker::Start(void*) /home/chiller/git/ddnet-insta/src/engine/server/databases/connection_pool.cpp:271:9
    #6 0x555556bc8d91 in thread_run(void*) /home/chiller/git/ddnet-insta/src/base/system.cpp:779:2
    #7 0x7ffff73c9143 in start_thread nptl/./nptl/pthread_create.c:442:8
    #8 0x7ffff74497db in clone3 misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```

**Comment by ChillerDragon** [comment]
Should be fixed by f7955a50e6a7c163d45fc3bbe40884dc2d4b628e

**Comment by ChillerDragon** [comment]
It is not fixed. It is now failing in the execute

```
$ cat SAN_bf5a9dab9b3a30b027c95270b116b2806afe3def_2024-10-10_03-45.148045 
/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/stl_vector.h:1124:9: runtime error: reference binding to null pointer of type 'st_mysql_bind'
    #0 0x55555604931c in std::vector<st_mysql_bind, std::allocator<st_mysql_bind> >::operator[](unsigned long) /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/stl_vector.h:1124:2
    #1 0x555556043414 in CMysqlConnection::ExecuteUpdate(int*, char*, int) /home/chiller/git/ddnet-insta/src/engine/server/databases/mysql.cpp:480:44
    #2 0x5555566c56c3 in CSqlStats::CreateTableThread(IDbConnection*, ISqlData const*, Write, char*, int) /home/chiller/git/ddnet-insta/src/game/server/instagib/sql_stats.cpp:1033:21
    #3 0x55555601b7ca in CDbConnectionPool::ExecSqlFunc(IDbConnection*, CSqlExecData*, Write) /home/chiller/git/ddnet-insta/src/engine/server/databases/connection_pool.cpp:454:14
    #4 0x55555601cfb1 in CWorker::ProcessQueries() /home/chiller/git/ddnet-insta/src/engine/server/databases/connection_pool.cpp:338:12
    #5 0x55555601bb98 in CWorker::Start(void*) /home/chiller/git/ddnet-insta/src/engine/server/databases/connection_pool.cpp:271:9
    #6 0x555556bce6c1 in thread_run(void*) /home/chiller/git/ddnet-insta/src/base/system.cpp:779:2
    #7 0x7ffff73c9143 in start_thread nptl/./nptl/pthread_create.c:442:8
    #8 0x7ffff74497db in clone3 misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/stl_vector.h:1124:9 in 
```

**Comment by ChillerDragon** [comment]
It now got fixed upstream. Two weeks without this asan error is rock solid evidence. Before the fix got shipped it happend multiple times a day.
